name: 'Setup Autify Command Line Interface (CLI)'
description: 'Install Autify CLI and add it to PATH'
author: 'Autify Inc.'

inputs:
  shell-installer-url:
    required: false
    description: 'Shell installer URL'
    # TODO: Use stable
    default: "https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/beta/install-cicd.bash"

runs:
  using: 'composite'
  steps:
    - if: ${{ inputs.install-cli-integration-test == 'true' }}
      uses: actions/setup-node@v3
    - run: $GITHUB_ACTION_PATH/script.bash
      shell: bash
      env:
        INPUT_SHELL_INSTALLER_URL: ${{ inputs.shell-installer-url }}
    - run: autify --version
      shell: bash
