name: 'Setup Autify Command Line Interface (CLI)'
description: 'Install Autify CLI and add it to PATH'
author: 'Autify Inc.'

inputs:
  shell-installer-url:
    required: false
    description: 'Shell installer URL'
    default: "https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/stable/install-cicd.bash"

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.bash
      shell: bash
      env:
        INPUT_SHELL_INSTALLER_URL: ${{ inputs.shell-installer-url }}
